[package]
name = "legend_shot"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.3"
egui = { version = "0.33.2", default-features = false, features = ["default_fonts"] }
eframe = { version = "0.33.2", default-features = false, features = ["glow", "accesskit", "x11"] }
egui-file-dialog = { version = "0.12.0", default-features = false }
chrono = { version = "0.4.42", default-features = false, features = ["std", "clock"] }
image = { version = "0.25.8", default-features = false, features = ["png", "jpeg"] }
xcap = "0.9.4"
device_query = "4.0.1"
clap = { version = "4.5", default-features = false, features = ["derive", "std"] }
serde = { version = "1", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1", default-features = false, features = ["std"] }
directories = "6.0"
oar-ocr = { version = "=0.7.0", features = ["auto-download"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar = "aarch64-linux-gnu-ar"

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig"
PKG_CONFIG_SYSROOT_DIR="/"


#[target.x86_64-pc-windows-gnu]
#linker = "x86_64-w64-mingw32-gcc"
#ar = "x86_64-w64-mingw32-gcc-ar"
#
#[target.i686-pc-windows-gnu]
#linker = "i686-w64-mingw32-gcc"
#ar = "i686-w64-mingw32-gcc-ar"
